#gitlab only
image: python:3.8-slim-buster
stages:
  - test
test:
  stage: test
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - python -m pip install --upgrade pip
  - pip install flake8
  - cd code
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
